
const sample=[{id:1,start:0,end:4,text:'Welcome to the English listening demo.',translation:'欢迎来到英语听力测试 Demo。'},{id:2,start:4,end:8.5,text:'Click any subtitle card to replay one sentence.',translation:'点击任意字幕卡片，可以重复播放一句话。'},{id:3,start:8.5,end:13,text:'You can hide Chinese and practise dictation.',translation:'你可以隐藏中文，练习听写。'},{id:4,start:13,end:17.5,text:'Try recording your voice after each line.',translation:'试着每一句后录下自己的声音。'},{id:5,start:17.5,end:22,text:'This short video is only for testing the app.',translation:'这个短视频只是用来测试网站功能。'}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const langs={
  zh:{pageTitle:'ShadowLoop',brandTitle:'ShadowLoop',brandTag:'精听 · 跟读 · 单句循环',tabs:{learn:'学习',saved:'收藏',notes:'笔记',help:'帮助'},theme:'主题',export:'导出记录',ytUrlPlaceholder:'粘贴 YouTube 链接，例如 https://www.youtube.com/watch?v=...',loadYt:'读取 YouTube',clearVideo:'清空',uploadVideo:'上传视频',uploadVideoDesc:'选择本地视频文件',importSub:'导入字幕',importSubDesc:'JSON / SRT / VTT',sample:'加载示例字幕',metaSent:'句子',metaDone:'已学',metaFav:'收藏',metaMode:'模式',metaModeValue:'本地保存',toolDictation:'听写模式',toolDictationDesc:'隐藏中文翻译。',dictationLabel:'开启',toolLoop:'单句循环',toolLoopDesc:'重复当前句子。',toolSpeed:'播放速度',toolSpeedDesc:'慢速精听。',toolRecord:'跟读录音',toolRecordDesc:'点句子里的麦克风。',stopRec:'停止录音',currentPractice:'当前练习',markDone:'标记已学',selectSentence:'选择右侧一句字幕开始。',placeholderTitle:'上传视频或粘贴 YouTube 链接',placeholderDesc:'本地 MP4 可以直接上传。YouTube 会嵌入播放器，字幕仍需导入 JSON / SRT / VTT。',dynamicSubs:'动态字幕',dynamicSubsDesc:'点击句子播放对应片段',filterAll:'全部',filterTodo:'未学',filterFav:'收藏',search:'搜索英文 / 中文 / 笔记',play:'▶ 播放',repeat:'🔁 循环',note:'📝 笔记',mic:'🎙️ 跟读',done:'✓ 已学',notePlaceholder:'给这句写一点笔记...',noTranslation:'暂无翻译',noMatch:'没有找到匹配的句子。',noSaved:'还没有收藏。',noNotes:'还没有笔记。',helpTitle:'使用说明',helpContent:'<div class="help"><ol><li>上传本地视频，或粘贴 YouTube 链接。</li><li>导入 JSON / SRT / VTT 字幕。</li><li>点击字幕卡片播放单句，点循环可重复播放。</li><li>录音功能需要 HTTPS 或 localhost，部署到 Vercel 后可用。</li><li>这个版本是单文件 index.html，上传 GitHub 最不容易丢文件。</li></ol></div>',alertNoTTS:'当前浏览器不支持点读语音。',alertNoYt:'没有识别到 YouTube 链接。试试 watch / youtu.be / shorts 链接。',alertYtFail:'YouTube API 加载失败，可能是网络或浏览器拦截。',alertMicNo:'当前浏览器不支持录音。Vercel/localhost 通常可以，普通 file:// 可能不稳定。',alertMicFail:'无法开启麦克风：',alertSubFail:'字幕解析失败：',langLabel:'语言',loopOptions:[{value:'1',label:'不循环'},{value:'2',label:'循环 2 遍'},{value:'3',label:'循环 3 遍'},{value:'5',label:'循环 5 遍'}],speedOptions:[{value:'0.7',label:'0.7x'},{value:'0.8',label:'0.8x'},{value:'0.9',label:'0.9x'},{value:'1',label:'1x'},{value:'1.25',label:'1.25x'}]},
  en:{pageTitle:'ShadowLoop',brandTitle:'ShadowLoop',brandTag:'Deep listening · Shadowing · Sentence loop',tabs:{learn:'Learn',saved:'Saved',notes:'Notes',help:'Help'},theme:'Theme',export:'Export progress',ytUrlPlaceholder:'Paste a YouTube link, e.g. https://www.youtube.com/watch?v=...',loadYt:'Load YouTube',clearVideo:'Clear',uploadVideo:'Upload video',uploadVideoDesc:'Select a local video file',importSub:'Import subtitles',importSubDesc:'JSON / SRT / VTT',sample:'Load sample subtitles',metaSent:'Sentences',metaDone:'Done',metaFav:'Favorites',metaMode:'Mode',metaModeValue:'Local save',toolDictation:'Dictation mode',toolDictationDesc:'Hide Chinese translation.',dictationLabel:'Enable',toolLoop:'Sentence loop',toolLoopDesc:'Repeat current sentence.',toolSpeed:'Playback speed',toolSpeedDesc:'Slow listening.',toolRecord:'Recording',toolRecordDesc:'Click the mic on a sentence.',stopRec:'Stop recording',currentPractice:'Current practice',markDone:'Mark done',selectSentence:'Select a subtitle on the right to start.',placeholderTitle:'Upload video or paste a YouTube link',placeholderDesc:'Local MP4 can be uploaded directly. YouTube embeds a player, but subtitles still need JSON / SRT / VTT.',dynamicSubs:'Dynamic subtitles',dynamicSubsDesc:'Click a sentence to replay the clip',filterAll:'All',filterTodo:'Todo',filterFav:'Fav',search:'Search English / Chinese / notes',play:'▶ Play',repeat:'🔁 Repeat',note:'📝 Note',mic:'🎙️ Record',done:'✓ Done',notePlaceholder:'Write a quick note for this sentence...',noTranslation:'No translation available',noMatch:'No matching sentences found.',noSaved:'No saved sentences yet.',noNotes:'No notes yet.',helpTitle:'How to use',helpContent:'<div class="help"><ol><li>Upload a local video or paste a YouTube link.</li><li>Import JSON / SRT / VTT subtitles.</li><li>Click a subtitle card to play one sentence; repeat will replay.</li><li>Recording requires HTTPS or localhost; deploy to Vercel for best results.</li><li>This version is a single-file index.html so it is easy to keep together.</li></ol></div>',alertNoTTS:'Your browser does not support text-to-speech.',alertNoYt:'No valid YouTube link detected. Try watch / youtu.be / shorts.',alertYtFail:'YouTube API failed to load, likely blocked by network or browser.',alertMicNo:'Your browser does not support recording. Works best on HTTPS or localhost.',alertMicFail:'Cannot access microphone: ',alertSubFail:'Subtitle parse failed: ',langLabel:'Language',loopOptions:[{value:'1',label:'No loop'},{value:'2',label:'Repeat 2x'},{value:'3',label:'Repeat 3x'},{value:'5',label:'Repeat 5x'}],speedOptions:[{value:'0.7',label:'0.7x'},{value:'0.8',label:'0.8x'},{value:'0.9',label:'0.9x'},{value:'1',label:'1x'},{value:'1.25',label:'1.25x'}]},}
const langNames={zh:'中文',en:'English'};
const st={subs:sample,active:null,filter:'all',q:'',fav:new Set(JSON.parse(localStorage.el_fav||'[]')),done:new Set(JSON.parse(localStorage.el_done||'[]')),notes:JSON.parse(localStorage.el_notes||'{}'),loopLeft:0,loopId:null,type:'local',yt:null,timer:null,rec:null,chunks:[],recs:[],lang:localStorage.el_lang||'zh'};
const video=$('#video');let ytApiReady=false;window.onYouTubeIframeAPIReady=()=>{ytApiReady=true};
function save(){localStorage.el_fav=JSON.stringify([...st.fav]);localStorage.el_done=JSON.stringify([...st.done]);localStorage.el_notes=JSON.stringify(st.notes);stats()}
function stats(){$('#count').textContent=st.subs.length;$('#doneCount').textContent=st.done.size;$('#favCount').textContent=st.fav.size}
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function t2s(v){const p=String(v).replace(',', '.').split(':').map(Number);if(p.length===3)return p[0]*3600+p[1]*60+p[2];if(p.length===2)return p[0]*60+p[1];return Number(v)||0}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')}
function parseText(txt){const clean=txt.replace(/^WEBVTT\s*/i,'').trim();return clean.split(/\n\s*\n/).map((b,i)=>{const lines=b.split('\n').map(x=>x.trim()).filter(Boolean);const ti=lines.findIndex(x=>x.includes('-->'));if(ti<0)return null;const [a,c]=lines[ti].split('-->').map(x=>x.trim().split(/\s+/)[0]);const content=lines.slice(ti+1);return{id:i+1,start:t2s(a),end:t2s(c),text:content[0]||'',translation:content.slice(1).join(' ')}}).filter(x=>x&&x.text)}
function normJson(j){const arr=Array.isArray(j)?j:(j.subtitles||j.items||[]);return arr.map((x,i)=>({id:x.id??i+1,start:Number(x.start??x.startTime??0),end:Number(x.end??x.endTime??((x.start??0)+3)),text:x.text||x.en||x.english||'',translation:x.translation||x.zh||x.chinese||''})).filter(x=>x.text)}
function visible(){return st.subs.filter(x=>{const n=st.notes[x.id]||'';const q=!st.q||[x.text,x.translation,n].join(' ').toLowerCase().includes(st.q);const f=st.filter==='all'||(st.filter==='todo'&&!st.done.has(String(x.id)))||(st.filter==='fav'&&st.fav.has(String(x.id)));return q&&f})}
function t(key){return langs[st.lang]?.[key] ?? langs.zh[key] ?? key}
function buildLangSelect(){const sel=$('#uiLang');sel.innerHTML=Object.entries(langNames).map(([code,name])=>`<option value="${code}">${name}</option>`).join('');sel.value=st.lang;sel.onchange=e=>{st.lang=e.target.value;localStorage.el_lang=st.lang;updateUIText();render()}}
function updateUIText(){const u=langs[st.lang];document.title=u.pageTitle;$('#brandTitle').textContent=u.brandTitle;$('#brandTag').textContent=u.brandTag;$('#loadYt').textContent=u.loadYt;$('#clearVideo').textContent=u.clearVideo;$('#sample').textContent=u.sample;$('#export').textContent=u.export;$('#placeholderTitle').textContent=u.placeholderTitle;$('#placeholderDesc').textContent=u.placeholderDesc;$('#uploadVideoLabel').textContent=u.uploadVideo;$('#uploadVideoDesc').textContent=u.uploadVideoDesc;$('#importSubLabel').textContent=u.importSub;$('#importSubDesc').textContent=u.importSubDesc;$('#ytUrl').placeholder=u.ytUrlPlaceholder;$('#search').placeholder=u.search;if($('#pillSent').firstChild)$('#pillSent').firstChild.textContent=u.metaSent+' ';if($('#pillDone').firstChild)$('#pillDone').firstChild.textContent=u.metaDone+' ';if($('#pillFav').firstChild)$('#pillFav').firstChild.textContent=u.metaFav+' ';if($('#pillMode').firstChild)$('#pillMode').firstChild.textContent=u.metaMode+' ';$('#modeValue').textContent=u.metaModeValue;$('#toolDictationTitle').textContent=u.toolDictation;$('#toolDictationDesc').textContent=u.toolDictationDesc;$('#dictationLabel').textContent=u.dictationLabel;$('#toolLoopTitle').textContent=u.toolLoop;$('#toolLoopDesc').textContent=u.toolLoopDesc;$('#toolSpeedTitle').textContent=u.toolSpeed;$('#toolSpeedDesc').textContent=u.toolSpeedDesc;$('#toolRecordTitle').textContent=u.toolRecord;$('#toolRecordDesc').textContent=u.toolRecordDesc;$('#stopRec').textContent=u.stopRec;$('#currentTitle').textContent=u.currentPractice;$('#markDone').textContent=u.markDone;$('#dynamicSubsTitle').textContent=u.dynamicSubs;$('#dynamicSubsDesc').textContent=u.dynamicSubsDesc;$$('.tab').forEach(b=>{b.textContent=u.tabs[b.dataset.panel]});$('#loop').innerHTML=u.loopOptions.map(o=>`<option value="${o.value}">${o.label}</option>`).join('');$('#speed').innerHTML=u.speedOptions.map(o=>`<option value="${o.value}">${o.label}</option>`).join('');$('#uiLang').title=u.langLabel}
function render(){stats();renderList();renderCurrent()}
function renderList(){const list=$('#list');const arr=visible();if(!arr.length){list.innerHTML=`<div class="empty">${t('noMatch')}</div>`;return}list.innerHTML='';arr.forEach(x=>{const d=document.createElement('article');d.className='card'+(String(x.id)===String(st.active)?' active':'')+(st.done.has(String(x.id))?' done':'');d.innerHTML=`<div class="cardTop"><span class="time">${fmt(x.start)}</span><button class="tiny star ${st.fav.has(String(x.id))?'active':''}">${st.fav.has(String(x.id))?'★':'☆'}</button></div><p class="en">${esc(x.text)}</p><p class="zh">${esc(x.translation||t('noTranslation'))}</p><textarea class="note ${st.notes[x.id]?'show':''}" placeholder="${esc(t('notePlaceholder'))}">${esc(st.notes[x.id]||'')}</textarea><div class="sentActions"><button class="tiny play">${t('play')}</button><button class="tiny repeat">${t('repeat')}</button><button class="tiny noteBtn">${t('note')}</button><button class="tiny mic">${t('mic')}</button><button class="tiny doneBtn ${st.done.has(String(x.id))?'active':''}">${t('done')}</button></div>`;d.querySelector('.play').onclick=()=>playSentence(x.id,false);d.querySelector('.repeat').onclick=()=>playSentence(x.id,true);d.querySelector('.star').onclick=()=>{const k=String(x.id);st.fav.has(k)?st.fav.delete(k):st.fav.add(k);save();render()};d.querySelector('.doneBtn').onclick=()=>{const k=String(x.id);st.done.has(k)?st.done.delete(k):st.done.add(k);save();render()};d.querySelector('.noteBtn').onclick=()=>d.querySelector('.note').classList.toggle('show');d.querySelector('.note').oninput=e=>{st.notes[x.id]=e.target.value;save()};d.querySelector('.mic').onclick=()=>startRec(x.id);list.appendChild(d)})}
function byId(id){return st.subs.find(x=>String(x.id)===String(id))}
function renderCurrent(){const x=byId(st.active);$('#current').className=x?'current':'current empty';$('#current').innerHTML=x?`<div class="enbig">${esc(x.text)}</div><div class="zhbig">${esc(x.translation||'')}</div>`:t('selectSentence')}
function curTime(){return st.type==='youtube'&&st.yt?.getCurrentTime?st.yt.getCurrentTime():video.currentTime||0}
function seek(s){if(st.type==='youtube'&&st.yt?.seekTo)st.yt.seekTo(s,true);else video.currentTime=s}
function canPlayMedia(){return st.type==='youtube'?!!st.yt:(!!video.currentSrc||!!video.src)}
function play(){if(st.type==='youtube'&&st.yt?.playVideo){st.yt.playVideo();return}const promise=video.play();if(promise?.catch){promise.catch(()=>{const x=byId(st.active||st.loopId);if(x){speakText(x.text)}else{alert(t('alertNoYt'))}})} }
function pause(){if(st.type==='youtube'&&st.yt?.pauseVideo)st.yt.pauseVideo();else video.pause()}
function rate(){const r=Number($('#speed').value);if(st.type==='youtube'&&st.yt?.setPlaybackRate){const a=st.yt.getAvailablePlaybackRates?.()||[.25,.5,.75,1,1.25,1.5,2];st.yt.setPlaybackRate(a.reduce((b,c)=>Math.abs(c-r)<Math.abs(b-r)?c:b,a[0]))}else video.playbackRate=r}
function playSentence(id,loop){const x=byId(id);if(!x)return;st.active=x.id;st.loopId=x.id;st.loopLeft=loop?Number($('#loop').value):1;if(canPlayMedia()){seek(Math.max(0,x.start+.02));rate();play()}else{readSentence(id)}render()}
function speakText(text){if(!('speechSynthesis' in window) || !('SpeechSynthesisUtterance' in window)){alert(t('alertNoTTS'));return}pause();speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';speechSynthesis.speak(u)}
function readSentence(id){const x=byId(id);if(!x)return;st.active=x.id;render();speakText(x.text)}
function tick(){const x=byId(st.loopId||st.active);if(!x||!st.loopLeft)return;if(curTime()>=x.end){st.loopLeft--;if(st.loopLeft>0){seek(x.start+.02);play()}else pause()}}
function ytId(u){try{const p=new URL(u);const h=p.hostname.replace(/^www\./,'');if(h==='youtu.be')return p.pathname.split('/').filter(Boolean)[0];if(h.endsWith('youtube.com')){if(p.pathname==='/watch')return p.searchParams.get('v');const parts=p.pathname.split('/').filter(Boolean);if(['embed','shorts','live'].includes(parts[0]))return parts[1]}}catch(e){if(/^[\w-]{11}$/.test(u))return u}return null}

async function fetchYouTubeTimedText(id,lang){
  // Try to fetch YouTube timedtext (XML). May be blocked by CORS in browsers.
  const url = `https://video.google.com/timedtext?lang=${encodeURIComponent(lang)}&v=${encodeURIComponent(id)}`;
  try{
    const res = await fetch(url);
    if(!res.ok) return null;
    const txt = await res.text();
    if(!txt.trim()) return null;
    const parser = new DOMParser();
    const xml = parser.parseFromString(txt,'application/xml');
    const texts = [...xml.querySelectorAll('text')];
    if(!texts.length) return null;
    const subs = texts.map((n,i)=>{
      const start = parseFloat(n.getAttribute('start')||0);
      const dur = parseFloat(n.getAttribute('dur')||0);
      const t = (n.textContent||'').replace(/\n+/g,' ').replace(/<[^>]+>/g,'').trim();
      return {id:i+1,start:endSafe(start),end:endSafe(start+ (dur||2)),text:t,translation:''};
    });
    return subs;
  }catch(e){
    return null;
  }
}

function endSafe(v){return Number.isFinite(v)?v:0}
function destroyYt(){if(st.timer)clearInterval(st.timer);st.timer=null;if(st.yt?.destroy)st.yt.destroy();st.yt=null;$('#yt').innerHTML=''}
function loadYt(){
  const id=ytId($('#ytUrl').value.trim());
  if(!id){alert(t('alertNoYt'));return}
  destroyYt();
  st.type='youtube';
  video.pause();video.removeAttribute('src');video.load();video.classList.add('hidden');
  $('#ph').classList.add('hidden');$('#yt').classList.remove('hidden');

  const create=()=>{st.yt=new YT.Player('yt',{videoId:id,playerVars:{playsinline:1,rel:0,modestbranding:1},events:{onReady:async ()=>{rate();st.timer=setInterval(tick,150);
        try{
          const tryLangs=['en','en-GB','en-US','zh'];
          for(const L of tryLangs){
            const subs = await fetchYouTubeTimedText(id, L);
            if(subs && subs.length){ st.subs = subs; st.active = null; render(); stats(); break }
          }
        }catch(err){console.warn('TimedText fetch error',err)}
      },onStateChange:e=>{if(e.data===0)st.loopLeft=0}}})};
  if(window.YT?.Player)create();else{let tries=0;const w=setInterval(()=>{tries++;if(window.YT?.Player){clearInterval(w);create()}else if(tries>80){clearInterval(w);alert(t('alertYtFail'));}} ,150)}
}
async function startRec(id){if(!navigator.mediaDevices?.getUserMedia){alert(t('alertMicNo'));return}if(st.rec?.state==='recording')stopRec();try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});st.chunks=[];st.rec=new MediaRecorder(stream);st.rec.ondataavailable=e=>st.chunks.push(e.data);st.rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(st.chunks,{type:'audio/webm'});const url=URL.createObjectURL(blob);st.recs.unshift({id,url,time:new Date().toLocaleString()});renderRecs()};st.rec.start();$('#stopRec').disabled=false;$('#stopRec').textContent=t('stopRec')+'...'}catch(e){alert(t('alertMicFail')+e.message)}}
function stopRec(){if(st.rec?.state==='recording')st.rec.stop();$('#stopRec').disabled=true;$('#stopRec').textContent=t('stopRec')}
function renderRecs(){const box=$('#recordings');box.innerHTML='';st.recs.forEach((r,i)=>{const d=document.createElement('div');d.className='rec';d.innerHTML=`<span>录音 ${i+1} · ${esc(r.time)}</span><a href="${r.url}" download="recording-${i+1}.webm">下载</a>`;box.appendChild(d)})}
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function mini(x,extra=''){return `<div class="miniItem"><strong>${esc(x.text)}</strong><p>${esc(x.translation||'')}</p>${extra?`<small>笔记：${esc(extra)}</small>`:''}</div>`}
function bind(){video.addEventListener('timeupdate',tick);$('#videoFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;destroyYt();st.type='local';video.src=URL.createObjectURL(f);video.classList.remove('hidden');$('#yt').classList.add('hidden');$('#ph').classList.add('hidden');rate()};$('#subFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const txt=await f.text();st.subs=f.name.toLowerCase().endsWith('.json')?normJson(JSON.parse(txt)):parseText(txt);st.active=null;render()}catch(err){alert(t('alertSubFail')+err.message)}};$('#sample').onclick=()=>{st.subs=sample;st.active=null;render()};$('#loadYt').onclick=loadYt;$('#ytUrl').onkeydown=e=>{if(e.key==='Enter')loadYt()};$('#clearVideo').onclick=()=>{destroyYt();st.type='local';video.pause();video.removeAttribute('src');video.load();video.classList.remove('hidden');$('#yt').classList.add('hidden');$('#ph').classList.remove('hidden');$('#ytUrl').value=''};$('#dictation').onchange=e=>document.body.classList.toggle('dictation',e.target.checked);$('#speed').onchange=rate;$('#search').oninput=e=>{st.q=e.target.value.trim().toLowerCase();renderList()};$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');st.filter=b.dataset.filter;renderList()});$('#markDone').onclick=()=>{if(!st.active)return;st.done.add(String(st.active));save();render()};$('#stopRec').onclick=stopRec;$('#theme').onclick=()=>{document.documentElement.classList.toggle('light');$('#theme').textContent=document.documentElement.classList.contains('light')?'☀':'☾'};$('#export').onclick=()=>{const data={exportedAt:new Date().toISOString(),subtitles:st.subs,favorites:[...st.fav],completed:[...st.done],notes:st.notes};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english-listening-progress.json';a.click();URL.revokeObjectURL(a.href)};$$('.tab').forEach(b=>b.onclick=()=>{if(b.dataset.panel==='learn')return; if(b.dataset.panel==='saved')modal(t('tabs').saved||t('saved'),st.subs.filter(x=>st.fav.has(String(x.id))).map(x=>mini(x)).join('')||`<div class="empty">${t('noSaved')}</div>`); if(b.dataset.panel==='notes')modal(t('tabs').notes||t('notes'),st.subs.filter(x=>st.notes[x.id]?.trim()).map(x=>mini(x,st.notes[x.id])).join('')||`<div class="empty">${t('noNotes')}</div>`); if(b.dataset.panel==='help')modal(t('helpTitle'),t('helpContent'))});$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')}}
document.addEventListener('DOMContentLoaded',()=>{bind();buildLangSelect();updateUIText();rate();render()});
